# Use the official Miniconda3 image as the base image
FROM continuumio/miniconda3

# Set the working directory in the container
WORKDIR /cf593_dicom

# Copy the current directory contents into the container
COPY . /cf593_dicom

# Create the Conda environment from your YAML file, excluding the problematic packages for now
RUN conda env create -f MI_environment.yml

# Activate the Conda environment
SHELL ["conda", "run", "-n", "MI_environment", "/bin/bash", "-c"]

# Ensure Python outputs are flushed immediately
ENV PYTHONUNBUFFERED=1

# Run the Python script
CMD ["conda", "run", "--no-capture-output", "-n", "MI_environment", "python", "handling_DICOM.py"]
