name: MI_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.12
  - numpy
  - pandas
  - pydicom
  - tqdm
  - matplotlib
  - pip
  - torchmetrics
  - pip:
    - torch==2.2.0
